config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "orders#index", as: "home"

  resources :orders
  resources :services
  resources :categories
  resources :executors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

end

app/models/executor.rb
class Executor < ApplicationRecord
  has_and_belongs_to_many :services
end

app/models/order.rb
class Order < ApplicationRecord
  has_and_belongs_to_many :services
end

app/models/service.rb
class Service < ApplicationRecord
  has_and_belongs_to_many :orders
  has_and_belongs_to_many :executors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def show
    # binding.pry
    @category = Category.find(params[:id])
  end

  def index
    @categories = Category.all
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    category = Category.find(params[:id])
    category.update(category_params)
    redirect_to categories_path
    # binding.pry
  end

  def create
    # binding.pry
    @category = Category.new(category_params)

    if @category.save
      # flash[:success] = 'Клиент создан успешно'
      redirect_to categories_path
    else
      # flash[:danger] = @client.errors.full_messages.join(', ')
      render :new
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/executors_controller.rb
class ExecutorsController < ApplicationController
  def new
    @executor = Executor.new
  end

  def show
    # binding.pry
    @executor = Executor.find(params[:id])
  end

  def index
    @executors = Executor.all
  end

  def edit
    @executor = Executor.find(params[:id])
  end

  def update
    executor = Executor.find(params[:id])
    executor.update(executor_params)
    redirect_to executors_path
    # binding.pry
  end

  def create
    # binding.pry
    @executor = Executor.new(executor_params)

    if @executor.save
      # flash[:success] = 'Клиент создан успешно'
      redirect_to executors_path
    else
      # flash[:danger] = @client.errors.full_messages.join(', ')
      render :new
    end
  end

  def destroy
    executor = Executor.find(params[:id])
    executor.destroy
    redirect_to executors_path
  end

  private

  def executor_params
    params.require(:executor).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController  < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    # binding.pry
    @order = Order.new
  end

  def index
    # binding.pry
    @orders = Order.all
  end

  def show
    # binding.pry
    @order = Order.find(params[:id])
  end

  def edit
    @order = Order.find(params[:id])
  end

  def create
    # binding.pry
    @order = Order.new(order_params)

    if @order.save
      # flash[:success] = 'Клиент создан успешно'
      redirect_to orders_path
    else
      # flash[:danger] = @client.errors.full_messages.join(', ')
      render :new
    end
  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)
    redirect_to orders_path
    # binding.pry
  end

  def destroy
    order = Order.find(params[:id])
    order.destroy
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit(:client, service_ids: [])
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def new
    @service = Service.new
  end

  def show
    @service = Service.find(params[:id])
    # binding.pry
  end

  def index
    @services = Service.all
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    service = Service.find(params[:id])
    service.update(service_params)
    redirect_to services_path
    # binding.pry
  end

  def create
    executor = Executor.find(params[:service][:executor_id])
    service = executor.services.new(service_params)
    # service = Service.new(service_params)
    # binding.pry
    if service.save
      executor.services << service
      redirect_to services_path
    else
      # flash[:danger] = @client.errors.full_messages.join(', ')
      render :new
    end
    # binding.pry
    # @service = Service.new(service_params)
    #
    # if @service.save
    #   # flash[:success] = 'Клиент создан успешно'
    #   redirect_to services_path
    # end
  end

  def destroy
    service = Service.find(params[:id])
    service.destroy
    redirect_to services_path
  end

  private

  def service_params
    params.require(:service).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/categories/edit.html.haml
.card
  .card-body
    %h1
      Категория услуги
    = form_with(model: @category) do |f|
      %fieldset.no-border-top
        .row
      .col-md-6.mb-3
        .mb-12
          = f.label :name, { class: "form-label"}
          .input-group.has-validation
            %span.input-group-text
              %i.fa-solid.fa-user-plus
            = f.text_field :name, { class: "form-control" }

        %br
        .form-buttons.filter-actions.actions
          = f.submit "Submit", class: "btn btn-primary"

app/views/categories/index.html.haml
.card
  .card-body.form-group
    %h1
      Категории услуг
    %a.btn.btn-outline-primary{href: new_category_path}
      = 'Новая услуга'
    %table.table.table-hover
      %thead
        %tr
          %th= 'id'
          %th= 'Название'
          %th= 'Дата создания'
          %th
      %tbodys
        - @categories.each do |category|
          %tr{style: "vertical-align: middle;"}
            %td= category.id
            %td= link_to category.name, category_path(category), { class: 'nav-link' }
            %td= category.created_at.strftime('%d.%m.%Y - %H:%M')
            %td
              = link_to "Редактировать", edit_category_path(category), :class => 'btn btn-warning'
              = link_to "Удалить", category_path(category), method: :delete, data: { confirm: "Вы уверены?" }, :class => 'btn btn-danger'

app/views/categories/new.html.haml
.card
  .card-body
    %h1
      Категория услуги
    = form_with(model: @category) do |f|
      %fieldset.no-border-top
        .row
      .col-md-6.mb-3
        .mb-12
          = f.label :name, { class: "form-label"}
          .input-group.has-validation
            %span.input-group-text
              %i.fa-solid.fa-user-plus
            = f.text_field :name, { class: "form-control" }

        %br
        .form-buttons.filter-actions.actions
          = f.submit "Submit", class: "btn btn-primary"

app/views/categories/show.html.haml
.card
  .card-body
    %h1
      = @category.name

app/views/executors/edit.html.haml
.card
  .card-body
    %h1
      Исполнитель услуги
    = form_with(model: @executor) do |f|
      %fieldset.no-border-top
        .row
      .col-md-6.mb-3
        .mb-12
          = f.label :name, { class: "form-label"}
          .input-group.has-validation
            %span.input-group-text
              %i.fa-solid.fa-user-plus
            = f.text_field :name, { class: "form-control" }
        .mb-12
          = f.label :service_id, { class: "form-label" }
          .input-group.has-validation
            %span.input-group-text
              %i.fa-solid.fa-at
            = f.select :service_id, Service.all.collect { |p| [ p.name, p.id ] }, { include_blank: true }, { class: "form-control", multiple: true }
        %br
        .form-buttons.filter-actions.actions
          = f.submit "Submit", class: "btn btn-primary"

app/views/executors/index.html.haml
.card
  .card-body.form-group
    %h1
      Исполнители услуг
    %a.btn.btn-outline-primary{href: new_executor_path}
      = 'Имя исполнителя'
    %table.table.table-hover
      %thead
        %tr
          %th= 'id'
          %th= 'Имя'
          %th= 'Дата создания'
          %th
      %tbodys
        - @executors.each do |executor|
          %tr{style: "vertical-align: middle;"}
            %td= executor.id
            %td= link_to executor.name, executor_path(executor), { class: 'nav-link' }
            %td= executor.created_at.strftime('%d.%m.%Y - %H:%M')
            %td
              = link_to "Редактировать", edit_executor_path(executor), :class => 'btn btn-warning'
              = link_to "Удалить", executor_path(executor), method: :delete, data: { confirm: "Вы уверены?" }, :class => 'btn btn-danger'

app/views/executors/new.html.haml
.card
  .card-body
    %h1
      Имя исполнителя
    = form_with(model: @executor) do |f|
      %fieldset.no-border-top
        .row
      .col-md-6.mb-3
        .mb-12
          = f.label :name, { class: "form-label"}
          .input-group.has-validation
            %span.input-group-text
              %i.fa-solid.fa-user-plus
            = f.text_field :name, { class: "form-control" }
        .mb-12
          = f.label :service_id, { class: "form-label" }
          .input-group.has-validation
            %span.input-group-text
              %i.fa-solid.fa-at
            = f.select :service_id, Service.all.collect { |p| [ p.name, p.id ] }, { include_blank: true }, { class: "form-control", multiple: true }
        %br
        .form-buttons.filter-actions.actions
          = f.submit "Submit", class: "btn btn-primary"

app/views/executors/show.html.haml
.card
  .card-body
    %h1
      = @executor.name
    - @executor.services.each do |service|
      = service.name

app/views/home/index.html.haml
Hello Everybody

app/views/layouts/_sidebar_navigation.html.haml
.flex-shrink-0.p-3.bg-white
  %a.d-flex.align-items-center.pb-3.mb-3.link-dark.text-decoration-none.border-bottom{:href => "/"}
    %svg.bi.me-4{:height => "24", :width => "30"}
      %use{"xlink:href" => "#bootstrap"}
    %span.fs-5.fw-semibold Меню:
  %ul.list-unstyled.ps-0
    #home-collapse.collapse.show
      %ul.btn-toggle-nav.list-unstyled.fw-normal.pb-1.small
        %li
          %a.link-dark.rounded{:href => orders_path } Заказы
        %li
          %a.link-dark.rounded{:href => services_path } Услуги
        %li
          %a.link-dark.rounded{:href => categories_path } Категория услуги
        %li
          %a.link-dark.rounded{:href => executors_path } Исполнитель услуги

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Autoservice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center pb-1 mb-3 border-bottom">
        <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
          <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title></svg>
          <span class="fs-1">AUTO SERVICE</span>
        </a>

        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
          <!-- <span class="me-4 py-2 text-dark text-decoration-none">gtgdgd</span> -->
        </nav>
      </div>
    <div class="container-fluid pb-3">
      <div class="d-grid gap-3" style="grid-template-columns: 1fr 5fr;">
        <div class="bg-light border rounded-3">
          <%= render "layouts/sidebar_navigation" %>
        </div>
        <div class="main-container">
          <%# flash.each do |k, v| %>
            <%# k = %w[alert error danger].include?(k) ? 'danger' : 'success' %>
            <%#= tag.div v, class: "alert alert-#{k} alert-dismissible", role: 'alert' %>
          <%# end %>
        <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/orders/_form.html.haml
.row
  .col-md-6.mb-3
    .mb-12
      = f.label :client, { class: "form-label"}
      .input-group.has-validation
        %span.input-group-text
          %i.fa-solid.fa-user-plus
        = f.text_field :client, { class: "form-control" }
    .mb-12
      = f.label :service_id, { class: "form-label"}
      .input-group.has-validation
        %span.input-group-text
          %i.fa-solid.fa-at
        = f.select :service_id, Service.all.collect { |p| [ p.name, p.id ] }, { include_blank: true }, { class: "form-control" }
-#    .mb-12
-#      = f.label :phone, { class: "form-label"}
-#      .input-group.has-validation
-#        %span.input-group-text
-#          %i.fa-solid.fa-phone
-#        = f.text_field :phone, { class: "form-control" }
-#    .mb-12
-#      = f.label :student_category, { class: "form-label"}
-#      .input-group.has-validation
-#        %span.input-group-text
-#          %i.fa-solid.fa-at
-#        = f.select :student_category_id, StudentCategory.all.collect { |p| [ p.name, p.id ] }, { include_blank: true }, { class: "form-control" }
-#    .mb-12
-#      = f.label :student_category, { class: "form-label"}
-#      .input-group.has-validation
-#        %span.input-group-text
-#          %i.fa-solid.fa-at
-#        = f.select :student_level_id, StudentLevel.all.collect { |p| [ p.name, p.id ] }, { include_blank: true }, { class: "form-control" }
-#  .col-md-6.mb-3
-#    .mb-12
-#      = f.label :email, { class: "form-label"}
-#      .input-group.has-validation
-#        %span.input-group-text
-#          %i.fa-solid.fa-at
-#        = f.text_field :email, { class: "form-control" }
-#    .mb-12
-#      = f.label :book, { class: "form-label"}
-#      .input-group.has-validation
-#        %span.input-group-text
-#          %i.fa-solid.fa-at
-#        = f.text_field :book, { class: "form-control" }
-#    .mb-12
-#      = f.label :tg, { class: "form-label"}
-#      .input-group.has-validation
-#        %span.input-group-text
-#          %i.fa-solid.fa-at
-#        = f.text_field :tg, { class: "form-control" }
-#    .mb-12
-#      = f.label :vk, { class: "form-label"}
-#      .input-group.has-validation
-#        %span.input-group-text
-#          %i.fa-solid.fa-at
-#        = f.text_field :vk, { class: "form-control" }
-#= hidden_field(:client, :user_id, { value: current_user.id })

app/views/orders/edit.html.haml
.card
  .card-body
    %h1
      Новый заказ
    = form_with(model: @order) do |f|
      %fieldset.no-border-top
        .row
      .col-md-6.mb-3
        .mb-12
          = f.label :client, { class: "form-label"}
          .input-group.has-validation
            %span.input-group-text
              %i.fa-solid.fa-user-plus
            = f.text_field :client, { class: "form-control" }
        .mb-12
          = f.label :service_id, { class: "form-label"}
          .input-group.has-validation
            %span.input-group-text
              %i.fa-solid.fa-at
            = f.select :service_ids, Service.all.collect { |p| [ p.name, p.id ] }, { include_blank: true }, { class: "form-control", multiple: true }
        %br
        .form-buttons.filter-actions.actions
          = f.submit "Submit", class: "btn btn-primary"

app/views/orders/index.html.haml
.card
  .card-body.form-group
    %h1
      Заказы
    %a.btn.btn-outline-primary{href: new_order_path}
      = 'Новый заказ'
    %table.table.table-hover
      %thead
        %tr
          %th= 'id'
          %th= 'Клиент'
          %th= 'Дата создания'
          %th
      %tbodys
        - @orders.each do |order|
          %tr{style: "vertical-align: middle;"}
            %td= order.id
            %td= link_to order.client, order_path(order), { class: 'nav-link' }
            %td= order.created_at.strftime('%d.%m.%Y - %H:%M')
            %td
              = link_to "Редактировать", edit_order_path(order), :class => 'btn btn-warning'
              = link_to "Удалить", order_path(order), method: :delete, data: { confirm: "Вы уверены?" }, :class => 'btn btn-danger'

app/views/orders/new.html.haml
.card
  .card-body
    %h1
      Новый заказ
    = form_with(model: @order) do |f|
      %fieldset.no-border-top
        .row
      .col-md-6.mb-3
        .mb-12
          = f.label :client, { class: "form-label"}
          .input-group.has-validation
            %span.input-group-text
              %i.fa-solid.fa-user-plus
            = f.text_field :client, { class: "form-control" }
        .mb-12
          = f.label :service_id, { class: "form-label" }
          .input-group.has-validation
            %span.input-group-text
              %i.fa-solid.fa-at
            = f.select :service_ids, Service.all.collect { |p| [ p.name, p.id ] }, { include_blank: true }, { class: "form-control", multiple: true }
        %br
        .form-buttons.filter-actions.actions
          = f.submit "Submit", class: "btn btn-primary"

app/views/orders/show.html.haml
.card
  .card-body
    %h1
      = @order.client
    - @order.services.each do |service|
      = service.name

app/views/services/edit.html.haml
.card
  .card-body
    %h1
      Новая услуга
    = form_with(model: @service) do |f|
      %fieldset.no-border-top
        .row
      .col-md-6.mb-3
        .mb-12
          = f.label :name, { class: "form-label"}
          .input-group.has-validation
            %span.input-group-text
              %i.fa-solid.fa-user-plus
            = f.text_field :name, { class: "form-control" }
        .mb-12
          = f.label :executor_id, { class: "form-label" }
          .input-group.has-validation
            %span.input-group-text
              %i.fa-solid.fa-at
            = f.select :executor_id, Executor.all.collect { |p| [ p.name, p.id ] }, { include_blank: true }, { class: "form-control", multiple: true }
        %br
        .form-buttons.filter-actions.actions
          = f.submit "Submit", class: "btn btn-primary"

app/views/services/index.html.haml
.card
  .card-body.form-group
    %h1
      Услуги
    %a.btn.btn-outline-primary{href: new_service_path}
      = 'Новая услуга'
    %table.table.table-hover
      %thead
        %tr
          %th= 'id'
          %th= 'Название'
          %th= 'Дата создания'
          %th
      %tbodys
        - @services.each do |service|
          %tr{style: "vertical-align: middle;"}
            %td= service.id
            %td= link_to service.name, service_path(service), { class: 'nav-link' }
            %td= service.created_at.strftime('%d.%m.%Y - %H:%M')
            %td
              = link_to "Редактировать", edit_service_path(service), :class => 'btn btn-warning'
              = link_to "Удалить", service_path(service), method: :delete, data: { confirm: "Вы уверены?" }, :class => 'btn btn-danger'

app/views/services/new.html.haml
.card
  .card-body
    %h1
      Новая услуга
    = form_with(model: @service) do |f|
      %fieldset.no-border-top
        .row
      .col-md-6.mb-3
        .mb-12
          = f.label :name, { class: "form-label"}
          .input-group.has-validation
            %span.input-group-text
              %i.fa-solid.fa-user-plus
            = f.text_field :name, { class: "form-control" }
        .mb-12
          = f.label :executor_id, { class: "form-label" }
          .input-group.has-validation
            %span.input-group-text
              %i.fa-solid.fa-at
            = f.select :executor_id, Executor.all.collect { |p| [ p.name, p.id ] }, { include_blank: true }, { class: "form-control" }
        %br
        .form-buttons.filter-actions.actions
          = f.submit "Submit", class: "btn btn-primary"

app/views/services/show.html.haml
.card
  .card-body
    %h1
      = @service.name
    - @service.executors.each do |executor|
      = executor.name